<?php require __DIR__.'/../common/header.php'; ?>

<h2>Payments</h2>
<table class="table table-stripped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Value</th>
            <th>Status</th>
        </tr>
    </thead>
    <tbody>
    <?php if (!empty($payments)){ ?>
        <?php foreach($payments as $payment) { ?>
            <tr>
                <td><?php echo $payment->id; ?></td>
                <td><?php echo '$ ', number_format($payment->value, 2); ?></td>
                <td><?php echo $payment->status; ?></td>
            </tr>
        <?php } ?>
    <?php } else{ ?>
        <tr>
            <td colspan="3">The list is empty</td>
        </tr>
    <?php } ?>
    </tbody>
</table>

<?php require __DIR__.'/../common/footer.php'; ?>
